import { IsString, IsEnum, IsOptional, IsBoolean, IsObject, IsArray, ValidateNested, Length } from 'class-validator';
import { Type } from 'class-transformer';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { ReportTemplateType, TemplateSection, TemplateVariables } from '../entities/report-template.entity';

export class CreateReportTemplateDto {
  @ApiProperty({
    description: 'Template name',
    example: 'Weekly League Summary',
    minLength: 2,
    maxLength: 255,
  })
  @IsString()
  @Length(2, 255)
  name: string;

  @ApiPropertyOptional({
    description: 'Template description',
    example: 'Weekly summary report including standings, top scorers, and upcoming games',
  })
  @IsOptional()
  @IsString()
  description?: string;

  @ApiProperty({
    description: 'Type of report template',
    enum: ReportTemplateType,
    example: ReportTemplateType.LEAGUE_SUMMARY,
  })
  @IsEnum(ReportTemplateType)
  templateType: ReportTemplateType;

  @ApiPropertyOptional({
    description: 'Template content configuration',
    example: {
      header: { showLogo: true, showDate: true },
      footer: { showPageNumbers: true, text: 'Generated by Gametriq' },
    },
  })
  @IsOptional()
  @IsObject()
  templateContent?: Record<string, any>;

  @ApiPropertyOptional({
    description: 'Template variables configuration',
    example: {
      dateRange: { type: 'number', required: true, default: 7 },
      includePhotos: { type: 'boolean', required: false, default: false },
    },
  })
  @IsOptional()
  @IsObject()
  variables?: TemplateVariables;

  @ApiPropertyOptional({
    description: 'Default filters to apply',
    example: { status: 'active', minGames: 1 },
  })
  @IsOptional()
  @IsObject()
  defaultFilters?: Record<string, any>;

  @ApiPropertyOptional({
    description: 'Report sections configuration',
    type: [Object],
    example: [
      {
        id: 'standings',
        type: 'table',
        title: 'Current Standings',
        columns: ['rank', 'team', 'wins', 'losses', 'pct'],
      },
    ],
  })
  @IsOptional()
  @IsArray()
  sections?: TemplateSection[];

  @ApiPropertyOptional({
    description: 'Styling configuration',
    example: { primaryColor: '#1f2937', fontSize: 12 },
  })
  @IsOptional()
  @IsObject()
  styling?: Record<string, any>;

  @ApiPropertyOptional({
    description: 'Whether this is a system template (read-only)',
    default: false,
  })
  @IsOptional()
  @IsBoolean()
  isSystem?: boolean;

  @ApiPropertyOptional({
    description: 'Whether the template is active',
    default: true,
  })
  @IsOptional()
  @IsBoolean()
  isActive?: boolean;
}