#!/bin/bash

echo "========================================"
echo "GameTriq Basketball League App Deployment"
echo "========================================"
echo ""
echo "This app is ready to deploy to Vercel!"
echo ""
echo "To deploy, follow these steps:"
echo ""
echo "1. First, login to Vercel:"
echo "   vercel login"
echo ""
echo "2. Then deploy to production:"
echo "   vercel --prod"
echo ""
echo "3. When prompted:"
echo "   - Select 'Y' to set up and deploy"
echo "   - Choose your scope/team"
echo "   - Link to existing project or create new one"
echo "   - Choose the current directory '.'"
echo ""
echo "The app will be deployed with:"
echo "- Supabase URL: https://mqfpbqvkhqjivqeqaclj.supabase.co"
echo "- All environment variables configured in vercel.json"
echo ""
echo "========================================"
echo "Alternative: Deploy via Vercel Dashboard"
echo "========================================"
echo ""
echo "1. Go to https://vercel.com/new"
echo "2. Import this Git repository"
echo "3. The environment variables are already in vercel.json"
echo "4. Click 'Deploy'"
echo ""
echo "========================================"